server:
 port: 8380

spring:
 application:
    name: doctor-service
 datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: ${DB_PASSWORD:shubh123456}
    url: ${JDBC_URL:jdbc:mariadb://localhost:3306/training}
    username: ${DB_USER:root}

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone:  ${EUREKA_SERVER:http://localhost:9190/eureka/}
debug: true 
